name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup Bun
        if: ${{ steps.release.outputs.release_created }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Pack and Upload
        if: ${{ steps.release.outputs.release_created }}
        run: |
          bun install
          npm pack
          gh release upload ${{ steps.release.outputs.tag_name }} *.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
